/*=============================================================================
   WARNING!!  This file is overwritten by the UIStyler each time the Styler 
   file is saved.
  
  
        Filename:  opu_cut_depths.h
  
        This file was generated by the NX User Interface Styler
        Created by: ChudoyakovEB68
        Version: NX 4
              Date: 01-26- 8
              Time: 12:50
  
   This include file is overwritten each time the UIStyler dialog is
   saved.  Any modifications to this file will be lost.
==============================================================================*/
 
 
#ifndef OPU_CUT_DEPTHS_H_INCLUDED
#define OPU_CUT_DEPTHS_H_INCLUDED
 
#include <uf.h> 
#include <uf_defs.h>
#include <uf_styler.h> 


#ifdef __cplusplus
extern "C" {
#endif


/*------------------ UIStyler Dialog Definitions  ------------------- */
/* The following values are definitions into your UIStyler dialog.    */
/* These values will allow you to modify existing objects within your */
/* dialog.   They work directly with the NX Open API,                 */
/* UF_STYLER_ask_value, UF_STYLER_ask_values, and UF_STYLER_set_value.*/
/*------------------------------------------------------------------- */
 
#define P_LABEL_TYPE                   ("LABEL_TYPE")
#define P_OPTION_TYPE                  ("OPTION_TYPE")
#define P_REAL_MAXIMUM                 ("REAL_MAXIMUM")
#define P_REAL_MINIMUM                 ("REAL_MINIMUM")
#define P_REAL_INITIAL                 ("REAL_INITIAL")
#define P_REAL_FINAL                   ("REAL_FINAL")
#define P_LABEL_INCREMENT              ("LABEL_INCREMENT")
#define P_REAL_INCREMENT               ("REAL_INCREMENT")
#define P_TOGGLE_TOP_OFF               ("TOGGLE_TOP_OFF")
#define P_DIALOG_OBJECT_COUNT          ( 9 )
 

/*---------------- UIStyler Callback Prototypes --------------- */
/* The following function prototypes define the callbacks       */
/* specified in your UIStyler built dialog.  You are REQUIRED to*/
/* create the associated function for each prototype.  You must */
/* use the same function name and parameter list when creating  */
/* your callback function.                                      */
/*------------------------------------------------------------- */

int P_construct_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int P_apply_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int P_type_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int P_real_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int P_tog_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);




#ifdef __cplusplus
}
#endif



#endif /* OPU_CUT_DEPTHS_H_INCLUDED */
